### ISSUE TITLE
Game Database

### ISSUE THREAD

**Issue by benckx** [benckx/elephantchess.io#4]
Page to view "reference games" (i.e. games played by professional players - the term "reference games" to distinct those games from the ones that will be played on the webapp later).

Similar to the puzzle UI (board + move history + contextual information (player, date, tournament name, was the game won by checkmate or resign/timeout, etc.))

In addition to those standard UI elements:
- it would be interesting to view alternative lines provided by the engine
- add some features to let users annotate games (they could later find those notes via the "my history" or "my games" menu items from the drop down menu).
- we could also show links to related games (games with similar opening, other games by those players)
- the UI should be similar to the Analysis Board, in such a way that we can easily switch from one another

New ideas:
- Create a ranking estimate for each player, as to be able to identify the most prominent players

**Comment by davide2024** [comment]
Could it be possible to download the commented game/games in a file format which can be printed? (like PGN)
Could the database receive new games inserted by users?
Could the engine self-analyze some games and give an idea of which moves were critical? 
To avoid to use too much the system, could it the main db file be downloaded on the local machine?

**Comment by benckx** [comment]
- Do you have examples of such format? Or examples of files you usually use? 
- I don't think I'd let anyone add games. Maybe I'll have an editor role to correct things or to improve player's profile (add chinese name, picture, bio, etc).
- I'm thinking I could add some analysis data in the db (and therefore start the analysis asynchronously and automatically on loading a game, if not analysed yet)
- I'm thinking I could add a data dump in CSV of all the games (like IMDB does for movies). The app has enough resources right now to handle many more users - and can be increased easily. So that's not an issue right now.
- What I could do is run the engine locally. I know Pikafish has a solution for this. But I never used this and that would be used locally only (i.e. play against the bot or play the puzzles).

**Comment by davide2024** [comment]
1. I do, in the sense that when one plays in Pychess all the games can be downloaded in a kind of PGN file which can be printed (do you want I send you the file on email or whatsapp so you can see it?). Unfortunately Pychess doesn't allow to add comments or variants when analysing a game and print it. 
2. I think it would be important to let some users to add games, because I do have many xiangqi books wits between champions like Hu Rong Hua, Li Lai Qun and many others. I also have games played between engines. 
3. Generally I analyze the games using XieXieMaster (definitely not the strongest engine, but at least self annotate the critical points, and gives the right move which should have been played - then of course it depends and one needs to be aware maybe the engine is not correct - I saw Fairy Stockfish is better on Winboard, but doesn't allow to write down comments and critical moves).

**Comment by benckx** [comment]
Games played between engines, you could import them as analysises.

Let's check when the database is fully uploaded if you have games that are missing.

I'm suspecting some player names I have with different spelling are actually the same person. Would be interesting to identify and fix those too.

**Comment by davide2024** [comment]
This is an example of PGN from Pychess:

[Event "PyChess casual game"]
[Site "https://www.pychess.org/tDcZpwrz"]
[Date "2023.03.09"]
[Round "-"]
[White "davide2023"]
[Black "Fairy-Stockfish"]
[Result "1-0"]
[TimeControl "600+20"]
[WhiteElo "1500?"]
[BlackElo "1500?"]
[Variant "Xiangqi"]
[FEN "rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1"]
[SetUp "1"]

1. Che3 Hg8 2. Hg3 Ch4 3. Pc5 Ece8 4. Hc3 Cc8 5. Hd5 Ha8 6. Cbc3 Pg6 7. Rb1 Rb10 8. Rxb10 Hxb10 9. Ri2 Hd9 10. Rf2 Ri9 11. Rf7 Rh9 12. Rg7 Rf9 13. Ade2 Ade9 14. Ccd3 Rf5 15. Hxe7 Hgxe7 16. Cxe7 Rxc5 17. Ece3 Rd5 18. Cxd9 Cb8 19. Ca9 Rd7 20. Pe5 Cb7 21. Pe6 Cb2 22. Rh7 Cb4 23. Pg5 Chf4 24. Pxg6 Kd10 25. Hf5 Pc6 26. Pd6 Rc7 27. Ph6 Pi6 28. Ce4 Rxh7 29. Pxh7 Ch4 30. He7 Cc4 31. Pxc6 Ch3 32. Pc7 Ch6 33. Cd4 Ke10 34. Ca10 Ce6 35. Kd1 Ca6 36. Cxa6 Pxa6 37. Ce4 Cxi4 38. Ce5 Cb4 39. Hd5 Ce4 40. Hb6 Cd4 41. Ha8 Kd10 42. Cd5 Ec10 43. Hc9 Kd9 44. Hd7+ Ad8 45. Hf8+ Ke9 46. Hxg10 Ea8 47. Pg7 Ec10 48. Pf7 Ee8 49. Hi9 Pi5 50. Pf8 Ec10 51. Hh7 Ph5 52. Pc8 Pa5 53. Pxa5 Ke10 54. Pc9 Ade9 55. Pf9 Ee8 56. Hf6 Ph4 57. Hxe8 Ad8 58. Hf6 Cf4 59. Hg8 Ade9 60. Ce5+ Af8 61. Pxf10+ Cxf10 62. Hxf10 Kxf10 63. Pd9 Pg4 64. Pa6 Ke10 65. Pb6 Ph4 66. Pc6 Pg4 67. Pd6 Ph4 68. Pe6+ Kf10 69. Pf6 Ph3 70. Pf7 Ke10 71. Pxf8 Ph2 72. Pf9 Pi2 73. Pde9# 1-0

**Comment by benckx** [comment]
How can you know which cannon has moved with `Che3`?

**Comment by davide2024** [comment]
Che3 the "h" tells you the departing square when two pieces can go into the same square (this is because it is horizxontal, Cbe3 would be the cannon on the"b" file). If instead it was vertical, let's say two cannons on the H file (obviously of the same color) it would be used the number of rank. Let's say in a fictional position there is a red cannon on H file 2nd rank and a red cannon H file 7th rank, and one wants to write the move: Ch5 he needs to specify which cannon, let's say the cannon on 2nd rank the move would be C2h5.

**Comment by benckx** [comment]
It's actually described in here, except they used different letters for some reasons:
https://en.wikipedia.org/wiki/Xiangqi#System_3

**Comment by davide2024** [comment]
Thank you.Great job as always.Remember to send me that bulletin you wanted to send to all subscribers.Let me know if I can help with anything.CiaoDavide

    On Sunday, July 30, 2023 at 11:14:05 AM EDT, benckx ***@***.***> wrote:  
 
 


Closed #4 as completed.
